In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [23]:
# File to read
org_dest_csv = "Resources/UN_MigrantStockByOriginAndDestination_2017.csv"
country_cat_csv = "Resources/Region_country_catalog.csv"

# Read data into Pandas data frame
org_dest_DF = pd.read_csv(org_dest_csv)
country_cat_DF = pd.read_csv(country_cat_csv)

In [24]:
# we need countries of origin, country of destination, total numbers of migrants, years
org_dest_DF = org_dest_DF.replace('..',0)

In [30]:
new_country_data = pd.merge(country_cat_DF,org_dest_DF, on="Country")

new_country_data.loc[new_country_data["Country"] == "United States of America"]

,Country,Region,Year,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,...,Uruguay,Uzbekistan,Vanuatu,Venezuela (Bolivarian Republic of),Viet Nam,Wallis and Futuna Islands,Western Sahara,Yemen,Zambia,Zimbabwe
820,United States of America,NORTHERN AMERICA,2005.0,"51,965","54,825","12,680",0,0,"7,294",0,...,"37,981","26,322",0,"142,706","1,106,433",0,0,"27,207","11,649","27,363"
821,United States of America,NORTHERN AMERICA,2010.0,"59,330","72,085","14,633",0,0,"10,411",0,...,"51,776","29,911",0,"180,905","1,236,000",0,0,"35,748","17,662","45,037"
822,United States of America,NORTHERN AMERICA,2015.0,"70,569","87,480","18,696",0,0,"13,397",0,...,"49,585","58,283",0,"224,986","1,363,825",0,0,"43,464","23,670","52,816"
823,United States of America,NORTHERN AMERICA,2017.0,"72,909","90,381","19,316",0,0,"13,841",0,...,"51,229","60,216",0,"232,448","1,409,063",0,0,"44,905","24,455","54,567"

In [39]:
for idx, value in new_country_data.iterrows():
    destination = value.Country
    reg_dest = value.Region
    year = value.Year
    #print(destination)
    origin_ctrs = value[3:]
    #print(origin_ctrs)

example = origin_ctrs.to_frame()
example

                                    915
Afghanistan                           0
Albania                               0
Algeria                               0
American Samoa                        0
Andorra                               0
Angola                                0
Anguilla                              0
Antigua and Barbuda                   0
Argentina                             0
Armenia                               0
Aruba                                 0
Australia                             0
Austria                               0
Azerbaijan                            0
Bahamas                               0
Bahrain                               0
Bangladesh                            0
Barbados                              0
Belarus                               0
Belgium                               0
Belize                                0
Benin                                 0
Bermuda                               0
Bhutan                                0
Bolivia (Plurinational State of)      0
Bosnia and Herzegovina                0
Botswana                              0
Brazil                                0
British Virgin Islands                0
Brunei Darussalam                     0
...                                 ...
Tajikistan                            0
TFYR Macedonia                        0
Thailand                              0
Timor-Leste                           0
Togo                                  0
Tokelau                               0
Tonga                                 0
Trinidad and Tobago                   0
Tunisia                               0
Turkey                                0
Turkmenistan                          0
Turks and Caicos Islands              0
Tuvalu                                0
Uganda                                0
Ukraine                               0
United Arab Emirates                  0
United Kingdom                        0
United Republic of Tanzania           0
United States of America              0
United States Virgin Islands          0
Uruguay                               0
Uzbekistan                            0
Vanuatu                             240
Venezuela (Bolivarian Republic of)    0
Viet Nam                              0
Wallis and Futuna Islands             0
Western Sahara                        0
Yemen                                 0
Zambia                                0
Zimbabwe                              0

[232 rows x 1 columns]